// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "StreamingDataWidthCo_2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic StreamingDataWidthCo_2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic StreamingDataWidthCo_2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> StreamingDataWidthCo_2::ap_ST_fsm_state1 = "1";
const sc_lv<8> StreamingDataWidthCo_2::ap_ST_fsm_state2 = "10";
const sc_lv<8> StreamingDataWidthCo_2::ap_ST_fsm_state3 = "100";
const sc_lv<8> StreamingDataWidthCo_2::ap_ST_fsm_state4 = "1000";
const sc_lv<8> StreamingDataWidthCo_2::ap_ST_fsm_state5 = "10000";
const sc_lv<8> StreamingDataWidthCo_2::ap_ST_fsm_state6 = "100000";
const sc_lv<8> StreamingDataWidthCo_2::ap_ST_fsm_pp0_stage0 = "1000000";
const sc_lv<8> StreamingDataWidthCo_2::ap_ST_fsm_state11 = "10000000";
const bool StreamingDataWidthCo_2::ap_const_boolean_1 = true;
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool StreamingDataWidthCo_2::ap_const_boolean_0 = false;
const sc_lv<1> StreamingDataWidthCo_2::ap_const_lv1_0 = "0";
const sc_lv<1> StreamingDataWidthCo_2::ap_const_lv1_1 = "1";
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_5 = "101";
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_6 = "110";
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_188 = "110001000";
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_1 = "1";
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_2 = "10";
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_20 = "100000";
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_3F = "111111";
const sc_lv<32> StreamingDataWidthCo_2::ap_const_lv32_7 = "111";

StreamingDataWidthCo_2::StreamingDataWidthCo_2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    BlackBoxJam_mul_3sc4_U186 = new BlackBoxJam_mul_3sc4<1,5,32,10,32>("BlackBoxJam_mul_3sc4_U186");
    BlackBoxJam_mul_3sc4_U186->clk(ap_clk);
    BlackBoxJam_mul_3sc4_U186->reset(ap_rst);
    BlackBoxJam_mul_3sc4_U186->din0(numReps_read_reg_179);
    BlackBoxJam_mul_3sc4_U186->din1(grp_fu_119_p1);
    BlackBoxJam_mul_3sc4_U186->ce(ap_var_for_const0);
    BlackBoxJam_mul_3sc4_U186->dout(grp_fu_119_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln268_reg_189_pp0_iter2_reg );
    sensitive << ( ap_predicate_op34_read_state9 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln268_reg_189_pp0_iter2_reg );
    sensitive << ( ap_predicate_op34_read_state9 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln268_reg_189_pp0_iter2_reg );
    sensitive << ( ap_predicate_op34_read_state9 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( numReps_empty_n );
    sensitive << ( numReps_out_full_n );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter3);
    sensitive << ( out_V_V_full_n );
    sensitive << ( icmp_ln268_reg_189_pp0_iter2_reg );

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter2);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_predicate_op34_read_state9 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state7);
    sensitive << ( icmp_ln268_fu_124_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_o_0_i_phi_fu_91_p4);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln268_reg_189 );
    sensitive << ( o_0_i_reg_87 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln282_fu_153_p3 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_p_Val2_s_phi_fu_113_p4);
    sensitive << ( icmp_ln268_reg_189_pp0_iter2_reg );
    sensitive << ( icmp_ln271_reg_208_pp0_iter2_reg );
    sensitive << ( ap_phi_reg_pp0_iter3_p_Val2_s_reg_110 );
    sensitive << ( zext_ln268_fu_159_p1 );

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_p_Val2_s_reg_110);

    SC_METHOD(thread_ap_predicate_op34_read_state9);
    sensitive << ( icmp_ln268_reg_189_pp0_iter1_reg );
    sensitive << ( icmp_ln271_reg_208 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_grp_fu_119_p1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_icmp_ln268_fu_124_p2);
    sensitive << ( t_0_i_reg_99 );
    sensitive << ( totalIters_reg_184 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln271_fu_147_p2);
    sensitive << ( icmp_ln268_reg_189 );
    sensitive << ( o_0_i_reg_87 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln282_fu_141_p2);
    sensitive << ( icmp_ln268_fu_124_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( o_fu_135_p2 );

    SC_METHOD(thread_in_V_V_blk_n);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln268_reg_189_pp0_iter1_reg );
    sensitive << ( icmp_ln271_reg_208 );

    SC_METHOD(thread_in_V_V_read);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_predicate_op34_read_state9 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_numReps_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_empty_n );

    SC_METHOD(thread_numReps_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_out_full_n );

    SC_METHOD(thread_numReps_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_dout );
    sensitive << ( numReps_empty_n );
    sensitive << ( numReps_out_full_n );

    SC_METHOD(thread_numReps_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_empty_n );
    sensitive << ( numReps_out_full_n );

    SC_METHOD(thread_numReps_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_empty_n );
    sensitive << ( numReps_out_full_n );

    SC_METHOD(thread_o_fu_135_p2);
    sensitive << ( ap_phi_mux_o_0_i_phi_fu_91_p4 );

    SC_METHOD(thread_out_V_V_blk_n);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln268_reg_189_pp0_iter2_reg );

    SC_METHOD(thread_out_V_V_din);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln268_reg_189_pp0_iter2_reg );
    sensitive << ( ap_phi_mux_p_Val2_s_phi_fu_113_p4 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_out_V_V_write);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln268_reg_189_pp0_iter2_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_select_ln282_fu_153_p3);
    sensitive << ( o_reg_198 );
    sensitive << ( icmp_ln282_reg_203 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_t_fu_129_p2);
    sensitive << ( t_0_i_reg_99 );

    SC_METHOD(thread_zext_ln268_fu_159_p1);
    sensitive << ( p_025_0_i_reg_75 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_empty_n );
    sensitive << ( numReps_out_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln268_fu_124_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    SC_THREAD(thread_ap_var_for_const0);

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000001";
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "StreamingDataWidthCo_2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, in_V_V_dout, "(port)in_V_V_dout");
    sc_trace(mVcdFile, in_V_V_empty_n, "(port)in_V_V_empty_n");
    sc_trace(mVcdFile, in_V_V_read, "(port)in_V_V_read");
    sc_trace(mVcdFile, out_V_V_din, "(port)out_V_V_din");
    sc_trace(mVcdFile, out_V_V_full_n, "(port)out_V_V_full_n");
    sc_trace(mVcdFile, out_V_V_write, "(port)out_V_V_write");
    sc_trace(mVcdFile, numReps_dout, "(port)numReps_dout");
    sc_trace(mVcdFile, numReps_empty_n, "(port)numReps_empty_n");
    sc_trace(mVcdFile, numReps_read, "(port)numReps_read");
    sc_trace(mVcdFile, numReps_out_din, "(port)numReps_out_din");
    sc_trace(mVcdFile, numReps_out_full_n, "(port)numReps_out_full_n");
    sc_trace(mVcdFile, numReps_out_write, "(port)numReps_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, in_V_V_blk_n, "in_V_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln268_reg_189, "icmp_ln268_reg_189");
    sc_trace(mVcdFile, icmp_ln268_reg_189_pp0_iter1_reg, "icmp_ln268_reg_189_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln271_reg_208, "icmp_ln271_reg_208");
    sc_trace(mVcdFile, out_V_V_blk_n, "out_V_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, icmp_ln268_reg_189_pp0_iter2_reg, "icmp_ln268_reg_189_pp0_iter2_reg");
    sc_trace(mVcdFile, numReps_blk_n, "numReps_blk_n");
    sc_trace(mVcdFile, numReps_out_blk_n, "numReps_out_blk_n");
    sc_trace(mVcdFile, p_025_0_i_reg_75, "p_025_0_i_reg_75");
    sc_trace(mVcdFile, o_0_i_reg_87, "o_0_i_reg_87");
    sc_trace(mVcdFile, t_0_i_reg_99, "t_0_i_reg_99");
    sc_trace(mVcdFile, numReps_read_reg_179, "numReps_read_reg_179");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, grp_fu_119_p2, "grp_fu_119_p2");
    sc_trace(mVcdFile, totalIters_reg_184, "totalIters_reg_184");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln268_fu_124_p2, "icmp_ln268_fu_124_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter0, "ap_block_state7_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter1, "ap_block_state8_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_predicate_op34_read_state9, "ap_predicate_op34_read_state9");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter2, "ap_block_state9_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter3, "ap_block_state10_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, t_fu_129_p2, "t_fu_129_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, o_fu_135_p2, "o_fu_135_p2");
    sc_trace(mVcdFile, o_reg_198, "o_reg_198");
    sc_trace(mVcdFile, icmp_ln282_fu_141_p2, "icmp_ln282_fu_141_p2");
    sc_trace(mVcdFile, icmp_ln282_reg_203, "icmp_ln282_reg_203");
    sc_trace(mVcdFile, icmp_ln271_fu_147_p2, "icmp_ln271_fu_147_p2");
    sc_trace(mVcdFile, icmp_ln271_reg_208_pp0_iter2_reg, "icmp_ln271_reg_208_pp0_iter2_reg");
    sc_trace(mVcdFile, select_ln282_fu_153_p3, "select_ln282_fu_153_p3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state7, "ap_condition_pp0_exit_iter0_state7");
    sc_trace(mVcdFile, ap_phi_mux_o_0_i_phi_fu_91_p4, "ap_phi_mux_o_0_i_phi_fu_91_p4");
    sc_trace(mVcdFile, ap_phi_mux_p_Val2_s_phi_fu_113_p4, "ap_phi_mux_p_Val2_s_phi_fu_113_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_p_Val2_s_reg_110, "ap_phi_reg_pp0_iter0_p_Val2_s_reg_110");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_p_Val2_s_reg_110, "ap_phi_reg_pp0_iter1_p_Val2_s_reg_110");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter2_p_Val2_s_reg_110, "ap_phi_reg_pp0_iter2_p_Val2_s_reg_110");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_p_Val2_s_reg_110, "ap_phi_reg_pp0_iter3_p_Val2_s_reg_110");
    sc_trace(mVcdFile, zext_ln268_fu_159_p1, "zext_ln268_fu_159_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, grp_fu_119_p1, "grp_fu_119_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

StreamingDataWidthCo_2::~StreamingDataWidthCo_2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete BlackBoxJam_mul_3sc4_U186;
}

void StreamingDataWidthCo_2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void StreamingDataWidthCo_2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state7.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state7.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state7.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            ap_enable_reg_pp0_iter3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        if ((esl_seteq<1,1,1>(icmp_ln268_reg_189_pp0_iter1_reg.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(icmp_ln271_reg_208.read(), ap_const_lv1_1))) {
            ap_phi_reg_pp0_iter3_p_Val2_s_reg_110 = in_V_V_dout.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter3_p_Val2_s_reg_110 = ap_phi_reg_pp0_iter2_p_Val2_s_reg_110.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln268_reg_189.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        o_0_i_reg_87 = select_ln282_fu_153_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        o_0_i_reg_87 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_reg_189_pp0_iter2_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_025_0_i_reg_75 = ap_phi_mux_p_Val2_s_phi_fu_113_p4.read().range(63, 32);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_025_0_i_reg_75 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_fu_124_p2.read()))) {
        t_0_i_reg_99 = t_fu_129_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        t_0_i_reg_99 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        ap_phi_reg_pp0_iter1_p_Val2_s_reg_110 = ap_phi_reg_pp0_iter0_p_Val2_s_reg_110.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_phi_reg_pp0_iter2_p_Val2_s_reg_110 = ap_phi_reg_pp0_iter1_p_Val2_s_reg_110.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln268_reg_189 = icmp_ln268_fu_124_p2.read();
        icmp_ln268_reg_189_pp0_iter1_reg = icmp_ln268_reg_189.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln268_reg_189_pp0_iter2_reg = icmp_ln268_reg_189_pp0_iter1_reg.read();
        icmp_ln271_reg_208_pp0_iter2_reg = icmp_ln271_reg_208.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln268_reg_189.read(), ap_const_lv1_0))) {
        icmp_ln271_reg_208 = icmp_ln271_fu_147_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_fu_124_p2.read()))) {
        icmp_ln282_reg_203 = icmp_ln282_fu_141_p2.read();
        o_reg_198 = o_fu_135_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_out_full_n.read())))) {
        numReps_read_reg_179 = numReps_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        totalIters_reg_184 = grp_fu_119_p2.read();
    }
}

void StreamingDataWidthCo_2::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[6];
}

void StreamingDataWidthCo_2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void StreamingDataWidthCo_2::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[7];
}

void StreamingDataWidthCo_2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void StreamingDataWidthCo_2::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void StreamingDataWidthCo_2::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void StreamingDataWidthCo_2::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_read_state9.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_reg_189_pp0_iter2_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read())));
}

void StreamingDataWidthCo_2::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_read_state9.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_reg_189_pp0_iter2_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read())));
}

void StreamingDataWidthCo_2::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_read_state9.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_reg_189_pp0_iter2_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read())));
}

void StreamingDataWidthCo_2::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_out_full_n.read()));
}

void StreamingDataWidthCo_2::thread_ap_block_state10_pp0_stage0_iter3() {
    ap_block_state10_pp0_stage0_iter3 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_reg_189_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()));
}

void StreamingDataWidthCo_2::thread_ap_block_state7_pp0_stage0_iter0() {
    ap_block_state7_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void StreamingDataWidthCo_2::thread_ap_block_state8_pp0_stage0_iter1() {
    ap_block_state8_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void StreamingDataWidthCo_2::thread_ap_block_state9_pp0_stage0_iter2() {
    ap_block_state9_pp0_stage0_iter2 = (esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_read_state9.read()));
}

void StreamingDataWidthCo_2::thread_ap_condition_pp0_exit_iter0_state7() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln268_fu_124_p2.read())) {
        ap_condition_pp0_exit_iter0_state7 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state7 = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void StreamingDataWidthCo_2::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void StreamingDataWidthCo_2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_ap_phi_mux_o_0_i_phi_fu_91_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln268_reg_189.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_phi_mux_o_0_i_phi_fu_91_p4 = select_ln282_fu_153_p3.read();
    } else {
        ap_phi_mux_o_0_i_phi_fu_91_p4 = o_0_i_reg_87.read();
    }
}

void StreamingDataWidthCo_2::thread_ap_phi_mux_p_Val2_s_phi_fu_113_p4() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_reg_189_pp0_iter2_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln271_reg_208_pp0_iter2_reg.read()))) {
        ap_phi_mux_p_Val2_s_phi_fu_113_p4 = zext_ln268_fu_159_p1.read();
    } else {
        ap_phi_mux_p_Val2_s_phi_fu_113_p4 = ap_phi_reg_pp0_iter3_p_Val2_s_reg_110.read();
    }
}

void StreamingDataWidthCo_2::thread_ap_phi_reg_pp0_iter0_p_Val2_s_reg_110() {
    ap_phi_reg_pp0_iter0_p_Val2_s_reg_110 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
}

void StreamingDataWidthCo_2::thread_ap_predicate_op34_read_state9() {
    ap_predicate_op34_read_state9 = (esl_seteq<1,1,1>(icmp_ln268_reg_189_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(icmp_ln271_reg_208.read(), ap_const_lv1_1));
}

void StreamingDataWidthCo_2::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void StreamingDataWidthCo_2::thread_grp_fu_119_p1() {
    grp_fu_119_p1 =  (sc_lv<10>) (ap_const_lv32_188);
}

void StreamingDataWidthCo_2::thread_icmp_ln268_fu_124_p2() {
    icmp_ln268_fu_124_p2 = (!t_0_i_reg_99.read().is_01() || !totalIters_reg_184.read().is_01())? sc_lv<1>(): sc_lv<1>(t_0_i_reg_99.read() == totalIters_reg_184.read());
}

void StreamingDataWidthCo_2::thread_icmp_ln271_fu_147_p2() {
    icmp_ln271_fu_147_p2 = (!o_0_i_reg_87.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(o_0_i_reg_87.read() == ap_const_lv32_0);
}

void StreamingDataWidthCo_2::thread_icmp_ln282_fu_141_p2() {
    icmp_ln282_fu_141_p2 = (!o_fu_135_p2.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<1>(): sc_lv<1>(o_fu_135_p2.read() == ap_const_lv32_2);
}

void StreamingDataWidthCo_2::thread_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln268_reg_189_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_ln271_reg_208.read(), ap_const_lv1_1))) {
        in_V_V_blk_n = in_V_V_empty_n.read();
    } else {
        in_V_V_blk_n = ap_const_logic_1;
    }
}

void StreamingDataWidthCo_2::thread_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op34_read_state9.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_V_V_read = ap_const_logic_1;
    } else {
        in_V_V_read = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_internal_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_numReps_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        numReps_blk_n = numReps_empty_n.read();
    } else {
        numReps_blk_n = ap_const_logic_1;
    }
}

void StreamingDataWidthCo_2::thread_numReps_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        numReps_out_blk_n = numReps_out_full_n.read();
    } else {
        numReps_out_blk_n = ap_const_logic_1;
    }
}

void StreamingDataWidthCo_2::thread_numReps_out_din() {
    numReps_out_din = numReps_dout.read();
}

void StreamingDataWidthCo_2::thread_numReps_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_out_full_n.read())))) {
        numReps_out_write = ap_const_logic_1;
    } else {
        numReps_out_write = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_numReps_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_out_full_n.read())))) {
        numReps_read = ap_const_logic_1;
    } else {
        numReps_read = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_o_fu_135_p2() {
    o_fu_135_p2 = (!ap_const_lv32_1.is_01() || !ap_phi_mux_o_0_i_phi_fu_91_p4.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(ap_phi_mux_o_0_i_phi_fu_91_p4.read()));
}

void StreamingDataWidthCo_2::thread_out_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_reg_189_pp0_iter2_reg.read()))) {
        out_V_V_blk_n = out_V_V_full_n.read();
    } else {
        out_V_V_blk_n = ap_const_logic_1;
    }
}

void StreamingDataWidthCo_2::thread_out_V_V_din() {
    out_V_V_din = ap_phi_mux_p_Val2_s_phi_fu_113_p4.read().range(32-1, 0);
}

void StreamingDataWidthCo_2::thread_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln268_reg_189_pp0_iter2_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_V_V_write = ap_const_logic_1;
    } else {
        out_V_V_write = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void StreamingDataWidthCo_2::thread_select_ln282_fu_153_p3() {
    select_ln282_fu_153_p3 = (!icmp_ln282_reg_203.read()[0].is_01())? sc_lv<32>(): ((icmp_ln282_reg_203.read()[0].to_bool())? ap_const_lv32_0: o_reg_198.read());
}

void StreamingDataWidthCo_2::thread_start_out() {
    start_out = real_start.read();
}

void StreamingDataWidthCo_2::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void StreamingDataWidthCo_2::thread_t_fu_129_p2() {
    t_fu_129_p2 = (!t_0_i_reg_99.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_0_i_reg_99.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void StreamingDataWidthCo_2::thread_zext_ln268_fu_159_p1() {
    zext_ln268_fu_159_p1 = esl_zext<64,32>(p_025_0_i_reg_75.read());
}

void StreamingDataWidthCo_2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, numReps_out_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 64 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln268_fu_124_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln268_fu_124_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

