# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Archana Narayanan/Desktop/BNN_project/BNN_edit/BNN_edit.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/procsys_BlackBoxJam_0_0.xci
# IP: The module: 'procsys_BlackBoxJam_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Archana Narayanan/Desktop/BNN_project/BNN_edit/BNN_edit.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/constraints/BlackBoxJam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'procsys_BlackBoxJam_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Archana Narayanan/Desktop/BNN_project/BNN_edit/BNN_edit.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/procsys_BlackBoxJam_0_0.xci
# IP: The module: 'procsys_BlackBoxJam_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Archana Narayanan/Desktop/BNN_project/BNN_edit/BNN_edit.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/constraints/BlackBoxJam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'procsys_BlackBoxJam_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
