-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ConvolutionInputGene_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_V_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    in_V_V_empty_n : IN STD_LOGIC;
    in_V_V_read : OUT STD_LOGIC;
    out_V_V_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    out_V_V_full_n : IN STD_LOGIC;
    out_V_V_write : OUT STD_LOGIC;
    numReps_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    numReps_empty_n : IN STD_LOGIC;
    numReps_read : OUT STD_LOGIC;
    numReps_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    numReps_out_full_n : IN STD_LOGIC;
    numReps_out_write : OUT STD_LOGIC );
end;


architecture behav of ConvolutionInputGene_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv46_0 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv46_1 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000001";
    constant ap_const_lv14_2004 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000100";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_10D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_V_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln107_reg_1003 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_reg_1047 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_V_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal icmp_ln107_reg_1003_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_1007 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_1007_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal numReps_blk_n : STD_LOGIC;
    signal numReps_out_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_307 : STD_LOGIC_VECTOR (45 downto 0);
    signal i_0_i_reg_318 : STD_LOGIC_VECTOR (13 downto 0);
    signal reg_396 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_predicate_op167_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_predicate_op221_write_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln107_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal numReps_read_reg_973 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal bound_fu_442_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal bound_reg_979 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln104_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln104_reg_984 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln104_fu_453_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln105_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln105_reg_993 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_471_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln107_reg_1003_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_1007_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln124_fu_524_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln124_reg_1011 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_line_in_bloc_fu_540_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_in_bloc_reg_1016 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln132_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln132_reg_1021 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_1025 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_fu_580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_1029 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_reg_1033 : STD_LOGIC_VECTOR (0 downto 0);
    signal ofm_y_fu_614_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_y_reg_1037 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln144_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_reg_1042 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln160_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln160_reg_1051 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_1056 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln129_fu_778_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln129_reg_1060 : STD_LOGIC_VECTOR (1 downto 0);
    signal outElem_V_fu_878_p6 : STD_LOGIC_VECTOR (23 downto 0);
    signal outElem_V_reg_1091 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal inputBuf_0_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_0_V_ce0 : STD_LOGIC;
    signal inputBuf_0_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal inputBuf_0_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_0_V_ce1 : STD_LOGIC;
    signal inputBuf_0_V_we1 : STD_LOGIC;
    signal inputBuf_1_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_1_V_ce0 : STD_LOGIC;
    signal inputBuf_1_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal inputBuf_1_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_1_V_ce1 : STD_LOGIC;
    signal inputBuf_1_V_we1 : STD_LOGIC;
    signal inputBuf_2_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_2_V_ce0 : STD_LOGIC;
    signal inputBuf_2_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal inputBuf_2_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_2_V_ce1 : STD_LOGIC;
    signal inputBuf_2_V_we1 : STD_LOGIC;
    signal inputBuf_3_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_3_V_ce0 : STD_LOGIC;
    signal inputBuf_3_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal inputBuf_3_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_3_V_ce1 : STD_LOGIC;
    signal inputBuf_3_V_we1 : STD_LOGIC;
    signal zext_ln129_fu_765_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln156_fu_794_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln110_fu_841_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_block_8_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln105_fu_485_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln160_fu_692_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_fu_750_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_y_1_i_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln144_3_fu_783_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_ofm_y_1_i_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_x_4_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_x_fu_594_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_4_fu_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_fu_528_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_4_fu_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln144_fu_626_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_fu_734_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_4_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_fu_563_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_4_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_fu_546_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_20_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_24_fu_829_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_21_fu_865_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_8_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln160_fu_676_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_372_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter_internal_blo_fu_136 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln172_fu_721_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln321_18_fu_802_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_fu_849_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_420_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_s_fu_431_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_shl_fu_427_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal p_shl70_fu_438_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln105_fu_465_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln128_fu_534_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_648_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln153_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln153_4_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln105_fu_493_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln163_fu_670_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal read_block_9_fu_684_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal counter_internal_blo_16_fu_709_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln172_fu_715_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln124_4_fu_761_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln129_3_fu_772_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_block_write_22_fu_809_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln165_fu_815_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_block_write_23_fu_821_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_fu_853_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln116_fu_859_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op175_store_state5 : BOOLEAN;
    signal ap_enable_operation_175 : BOOLEAN;
    signal ap_enable_state5_pp0_iter2_stage0 : BOOLEAN;
    signal ap_predicate_op159_load_state5 : BOOLEAN;
    signal ap_enable_operation_159 : BOOLEAN;
    signal ap_predicate_op218_load_state6 : BOOLEAN;
    signal ap_enable_operation_218 : BOOLEAN;
    signal ap_enable_state6_pp0_iter3_stage0 : BOOLEAN;
    signal ap_predicate_op202_store_state5 : BOOLEAN;
    signal ap_enable_operation_202 : BOOLEAN;
    signal ap_predicate_op177_store_state5 : BOOLEAN;
    signal ap_enable_operation_177 : BOOLEAN;
    signal ap_predicate_op157_load_state5 : BOOLEAN;
    signal ap_enable_operation_157 : BOOLEAN;
    signal ap_predicate_op217_load_state6 : BOOLEAN;
    signal ap_enable_operation_217 : BOOLEAN;
    signal ap_predicate_op204_store_state5 : BOOLEAN;
    signal ap_enable_operation_204 : BOOLEAN;
    signal ap_predicate_op179_store_state5 : BOOLEAN;
    signal ap_enable_operation_179 : BOOLEAN;
    signal ap_predicate_op155_load_state5 : BOOLEAN;
    signal ap_enable_operation_155 : BOOLEAN;
    signal ap_predicate_op216_load_state6 : BOOLEAN;
    signal ap_enable_operation_216 : BOOLEAN;
    signal ap_predicate_op206_store_state5 : BOOLEAN;
    signal ap_enable_operation_206 : BOOLEAN;
    signal ap_predicate_op181_store_state5 : BOOLEAN;
    signal ap_enable_operation_181 : BOOLEAN;
    signal ap_predicate_op161_load_state5 : BOOLEAN;
    signal ap_enable_operation_161 : BOOLEAN;
    signal ap_predicate_op219_load_state6 : BOOLEAN;
    signal ap_enable_operation_219 : BOOLEAN;
    signal ap_predicate_op208_store_state5 : BOOLEAN;
    signal ap_enable_operation_208 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_438 : BOOLEAN;
    signal ap_condition_450 : BOOLEAN;
    signal ap_condition_461 : BOOLEAN;
    signal ap_condition_472 : BOOLEAN;

    component BlackBoxJam_mux_4fYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component ConvolutionInputGbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    inputBuf_0_V_U : component ConvolutionInputGbkb
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_0_V_address0,
        ce0 => inputBuf_0_V_ce0,
        q0 => inputBuf_0_V_q0,
        address1 => inputBuf_0_V_address1,
        ce1 => inputBuf_0_V_ce1,
        we1 => inputBuf_0_V_we1,
        d1 => in_V_V_dout);

    inputBuf_1_V_U : component ConvolutionInputGbkb
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_1_V_address0,
        ce0 => inputBuf_1_V_ce0,
        q0 => inputBuf_1_V_q0,
        address1 => inputBuf_1_V_address1,
        ce1 => inputBuf_1_V_ce1,
        we1 => inputBuf_1_V_we1,
        d1 => in_V_V_dout);

    inputBuf_2_V_U : component ConvolutionInputGbkb
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_2_V_address0,
        ce0 => inputBuf_2_V_ce0,
        q0 => inputBuf_2_V_q0,
        address1 => inputBuf_2_V_address1,
        ce1 => inputBuf_2_V_ce1,
        we1 => inputBuf_2_V_we1,
        d1 => in_V_V_dout);

    inputBuf_3_V_U : component ConvolutionInputGbkb
    generic map (
        DataWidth => 24,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_3_V_address0,
        ce0 => inputBuf_3_V_ce0,
        q0 => inputBuf_3_V_q0,
        address1 => inputBuf_3_V_address1,
        ce1 => inputBuf_3_V_ce1,
        we1 => inputBuf_3_V_we1,
        d1 => in_V_V_dout);

    BlackBoxJam_mux_4fYi_U33 : component BlackBoxJam_mux_4fYi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        din2_WIDTH => 24,
        din3_WIDTH => 24,
        din4_WIDTH => 2,
        dout_WIDTH => 24)
    port map (
        din0 => inputBuf_0_V_q0,
        din1 => inputBuf_1_V_q0,
        din2 => inputBuf_2_V_q0,
        din3 => inputBuf_3_V_q0,
        din4 => add_ln129_reg_1060,
        dout => outElem_V_fu_878_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_simd_4_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln132_fu_552_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                count_simd_4_fu_124 <= count_simd_fu_546_p2;
            elsif ((((icmp_ln135_fu_569_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln138_fu_580_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln141_fu_600_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln141_fu_600_p2 = ap_const_lv1_1) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                count_simd_4_fu_124 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    counter_internal_blo_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                counter_internal_blo_fu_136 <= select_ln172_fu_721_p3;
            elsif ((((icmp_ln113_fu_384_p2 = ap_const_lv1_1) and (icmp_ln107_fu_497_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                counter_internal_blo_fu_136 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_block_write_20_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln113_reg_1056 = ap_const_lv1_1) and (icmp_ln107_reg_1003 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_block_write_20_fu_128 <= current_block_write_21_fu_865_p3;
            elsif (((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_block_write_20_fu_128 <= current_block_write_24_fu_829_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_block_write_20_fu_128 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_line_8_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln113_fu_384_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_line_8_fu_132 <= grp_fu_372_p2;
            elsif (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln153_fu_664_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_line_8_fu_132 <= select_ln160_fu_676_p3;
            elsif ((((icmp_ln113_fu_384_p2 = ap_const_lv1_1) and (icmp_ln107_fu_497_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                current_line_8_fu_132 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_0_i_reg_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_448_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_0_i_reg_318 <= i_fu_471_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                i_0_i_reg_318 <= ap_const_lv14_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_307_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_448_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_307 <= add_ln104_fu_453_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                indvar_flatten_reg_307 <= ap_const_lv46_0;
            end if; 
        end if;
    end process;

    inp_4_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                inp_4_fu_116 <= inp_fu_734_p2;
            elsif (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln141_fu_600_p2 = ap_const_lv1_1) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                inp_4_fu_116 <= select_ln144_fu_626_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                inp_4_fu_116 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_x_4_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln135_fu_569_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_x_4_fu_120 <= k_x_fu_563_p2;
            elsif ((((icmp_ln138_fu_580_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln141_fu_600_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln141_fu_600_p2 = ap_const_lv1_1) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_x_4_fu_120 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_y_4_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln138_fu_580_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_y_4_fu_112 <= k_y_fu_528_p2;
            elsif ((((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_y_4_fu_112 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_x_4_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln141_fu_600_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ofm_x_4_fu_108 <= ofm_x_fu_594_p2;
            elsif ((((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln141_fu_600_p2 = ap_const_lv1_1) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                ofm_x_4_fu_108 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_y_1_i_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_reg_1007 = ap_const_lv1_1) and (icmp_ln141_reg_1033 = ap_const_lv1_1) and (icmp_ln138_reg_1029 = ap_const_lv1_1) and (icmp_ln135_reg_1025 = ap_const_lv1_1) and (icmp_ln132_reg_1021 = ap_const_lv1_1) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ofm_y_1_i_fu_104 <= select_ln144_3_fu_783_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ofm_y_1_i_fu_104 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    read_block_8_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln113_fu_384_p2 = ap_const_lv1_1) and (icmp_ln107_fu_497_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                read_block_8_fu_100 <= read_block_fu_750_p2;
            elsif (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln153_fu_664_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                read_block_8_fu_100 <= zext_ln160_fu_692_p1;
            elsif ((((icmp_ln113_fu_384_p2 = ap_const_lv1_0) and (icmp_ln107_fu_497_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_lv1_0 = and_ln153_fu_664_p2) and (icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                read_block_8_fu_100 <= select_ln105_fu_485_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                read_block_8_fu_100 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_reg_1007 = ap_const_lv1_1) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln129_reg_1060 <= add_ln129_fu_778_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln153_reg_1047 <= and_ln153_fu_664_p2;
                icmp_ln123_reg_1007 <= icmp_ln123_fu_506_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    bound_reg_979(45 downto 2) <= bound_fu_442_p2(45 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                current_line_in_bloc_reg_1016 <= current_line_in_bloc_fu_540_p2;
                icmp_ln132_reg_1021 <= icmp_ln132_fu_552_p2;
                trunc_ln124_reg_1011 <= trunc_ln124_fu_524_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln104_reg_984 <= icmp_ln104_fu_448_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_448_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln105_reg_993 <= icmp_ln105_fu_459_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_reg_984 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln107_reg_1003 <= icmp_ln107_fu_497_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln107_reg_1003_pp0_iter2_reg <= icmp_ln107_reg_1003;
                icmp_ln107_reg_1003_pp0_iter3_reg <= icmp_ln107_reg_1003_pp0_iter2_reg;
                icmp_ln123_reg_1007_pp0_iter2_reg <= icmp_ln123_reg_1007;
                icmp_ln123_reg_1007_pp0_iter3_reg <= icmp_ln123_reg_1007_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln113_reg_1056 <= icmp_ln113_fu_384_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln135_reg_1025 <= icmp_ln135_fu_569_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln138_reg_1029 <= icmp_ln138_fu_580_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln141_reg_1033 <= icmp_ln141_fu_600_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (icmp_ln141_fu_600_p2 = ap_const_lv1_1) and (icmp_ln138_fu_580_p2 = ap_const_lv1_1) and (icmp_ln135_fu_569_p2 = ap_const_lv1_1) and (icmp_ln132_fu_552_p2 = ap_const_lv1_1) and (icmp_ln123_fu_506_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln144_reg_1042 <= icmp_ln144_fu_620_p2;
                ofm_y_reg_1037 <= ofm_y_fu_614_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln153_fu_664_p2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln160_reg_1051 <= icmp_ln160_fu_378_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                numReps_read_reg_973 <= numReps_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_reg_1003_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln123_reg_1007_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                outElem_V_reg_1091 <= outElem_V_fu_878_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln107_fu_497_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_fu_497_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln153_fu_664_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                reg_396 <= current_line_8_fu_132;
            end if;
        end if;
    end process;
    bound_reg_979(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, icmp_ln104_fu_448_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln104_fu_448_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln104_fu_448_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln104_fu_453_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_307) + unsigned(ap_const_lv46_1));
    add_ln105_fu_465_p2 <= std_logic_vector(unsigned(i_0_i_reg_318) + unsigned(ap_const_lv14_1));
    add_ln128_fu_534_p2 <= std_logic_vector(unsigned(ofm_x_4_fu_108) + unsigned(count_simd_4_fu_124));
    add_ln129_3_fu_772_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(trunc_ln124_4_fu_761_p1));
    add_ln129_fu_778_p2 <= std_logic_vector(unsigned(add_ln129_3_fu_772_p2) + unsigned(trunc_ln124_reg_1011));
    add_ln163_fu_670_p2 <= std_logic_vector(unsigned(trunc_ln105_fu_493_p1) + unsigned(ap_const_lv6_1));
    and_ln153_fu_664_p2 <= (icmp_ln153_fu_642_p2 and icmp_ln153_4_fu_658_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state8 <= ap_CS_fsm(3);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, ap_enable_reg_pp0_iter4, ap_predicate_op167_read_state5, ap_predicate_op221_write_state7)
    begin
                ap_block_pp0_stage0_01001 <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op221_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op167_read_state5 = ap_const_boolean_1)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, ap_enable_reg_pp0_iter4, ap_predicate_op167_read_state5, ap_predicate_op221_write_state7)
    begin
                ap_block_pp0_stage0_11001 <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op221_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op167_read_state5 = ap_const_boolean_1)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, ap_enable_reg_pp0_iter4, ap_predicate_op167_read_state5, ap_predicate_op221_write_state7)
    begin
                ap_block_pp0_stage0_subdone <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op221_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op167_read_state5 = ap_const_boolean_1)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, numReps_empty_n, numReps_out_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter2_assign_proc : process(in_V_V_empty_n, icmp_ln107_reg_1003, ap_predicate_op167_read_state5)
    begin
                ap_block_state5_pp0_stage0_iter2 <= (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op167_read_state5 = ap_const_boolean_1)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)));
    end process;

        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_pp0_stage0_iter4_assign_proc : process(out_V_V_full_n, ap_predicate_op221_write_state7)
    begin
                ap_block_state7_pp0_stage0_iter4 <= ((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op221_write_state7 = ap_const_boolean_1));
    end process;


    ap_condition_438_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047, trunc_ln321_18_fu_802_p1)
    begin
                ap_condition_438 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_0));
    end process;


    ap_condition_450_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047, trunc_ln321_18_fu_802_p1)
    begin
                ap_condition_450 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_1));
    end process;


    ap_condition_461_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047, trunc_ln321_18_fu_802_p1)
    begin
                ap_condition_461 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_2));
    end process;


    ap_condition_472_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047, trunc_ln321_18_fu_802_p1)
    begin
                ap_condition_472 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_3));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln104_fu_448_p2)
    begin
        if ((icmp_ln104_fu_448_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_155_assign_proc : process(ap_predicate_op155_load_state5)
    begin
                ap_enable_operation_155 <= (ap_predicate_op155_load_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_157_assign_proc : process(ap_predicate_op157_load_state5)
    begin
                ap_enable_operation_157 <= (ap_predicate_op157_load_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_159_assign_proc : process(ap_predicate_op159_load_state5)
    begin
                ap_enable_operation_159 <= (ap_predicate_op159_load_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_161_assign_proc : process(ap_predicate_op161_load_state5)
    begin
                ap_enable_operation_161 <= (ap_predicate_op161_load_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_175_assign_proc : process(ap_predicate_op175_store_state5)
    begin
                ap_enable_operation_175 <= (ap_predicate_op175_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_177_assign_proc : process(ap_predicate_op177_store_state5)
    begin
                ap_enable_operation_177 <= (ap_predicate_op177_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_179_assign_proc : process(ap_predicate_op179_store_state5)
    begin
                ap_enable_operation_179 <= (ap_predicate_op179_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_181_assign_proc : process(ap_predicate_op181_store_state5)
    begin
                ap_enable_operation_181 <= (ap_predicate_op181_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_202_assign_proc : process(ap_predicate_op202_store_state5)
    begin
                ap_enable_operation_202 <= (ap_predicate_op202_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_204_assign_proc : process(ap_predicate_op204_store_state5)
    begin
                ap_enable_operation_204 <= (ap_predicate_op204_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_206_assign_proc : process(ap_predicate_op206_store_state5)
    begin
                ap_enable_operation_206 <= (ap_predicate_op206_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_208_assign_proc : process(ap_predicate_op208_store_state5)
    begin
                ap_enable_operation_208 <= (ap_predicate_op208_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_216_assign_proc : process(ap_predicate_op216_load_state6)
    begin
                ap_enable_operation_216 <= (ap_predicate_op216_load_state6 = ap_const_boolean_1);
    end process;


    ap_enable_operation_217_assign_proc : process(ap_predicate_op217_load_state6)
    begin
                ap_enable_operation_217 <= (ap_predicate_op217_load_state6 = ap_const_boolean_1);
    end process;


    ap_enable_operation_218_assign_proc : process(ap_predicate_op218_load_state6)
    begin
                ap_enable_operation_218 <= (ap_predicate_op218_load_state6 = ap_const_boolean_1);
    end process;


    ap_enable_operation_219_assign_proc : process(ap_predicate_op219_load_state6)
    begin
                ap_enable_operation_219 <= (ap_predicate_op219_load_state6 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_state5_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage0)
    begin
                ap_enable_state5_pp0_iter2_stage0 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_enable_state6_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3)
    begin
                ap_enable_state6_pp0_iter3_stage0 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op155_load_state5_assign_proc : process(icmp_ln107_reg_1003, icmp_ln123_reg_1007)
    begin
                ap_predicate_op155_load_state5 <= ((icmp_ln123_reg_1007 = ap_const_lv1_1) and (icmp_ln107_reg_1003 = ap_const_lv1_0));
    end process;


    ap_predicate_op157_load_state5_assign_proc : process(icmp_ln107_reg_1003, icmp_ln123_reg_1007)
    begin
                ap_predicate_op157_load_state5 <= ((icmp_ln123_reg_1007 = ap_const_lv1_1) and (icmp_ln107_reg_1003 = ap_const_lv1_0));
    end process;


    ap_predicate_op159_load_state5_assign_proc : process(icmp_ln107_reg_1003, icmp_ln123_reg_1007)
    begin
                ap_predicate_op159_load_state5 <= ((icmp_ln123_reg_1007 = ap_const_lv1_1) and (icmp_ln107_reg_1003 = ap_const_lv1_0));
    end process;


    ap_predicate_op161_load_state5_assign_proc : process(icmp_ln107_reg_1003, icmp_ln123_reg_1007)
    begin
                ap_predicate_op161_load_state5 <= ((icmp_ln123_reg_1007 = ap_const_lv1_1) and (icmp_ln107_reg_1003 = ap_const_lv1_0));
    end process;


    ap_predicate_op167_read_state5_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047)
    begin
                ap_predicate_op167_read_state5 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0));
    end process;


    ap_predicate_op175_store_state5_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047, trunc_ln321_18_fu_802_p1)
    begin
                ap_predicate_op175_store_state5 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_2));
    end process;


    ap_predicate_op177_store_state5_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047, trunc_ln321_18_fu_802_p1)
    begin
                ap_predicate_op177_store_state5 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_1));
    end process;


    ap_predicate_op179_store_state5_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047, trunc_ln321_18_fu_802_p1)
    begin
                ap_predicate_op179_store_state5 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_0));
    end process;


    ap_predicate_op181_store_state5_assign_proc : process(icmp_ln107_reg_1003, and_ln153_reg_1047, trunc_ln321_18_fu_802_p1)
    begin
                ap_predicate_op181_store_state5 <= ((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_3));
    end process;


    ap_predicate_op202_store_state5_assign_proc : process(icmp_ln107_reg_1003, trunc_ln321_fu_849_p1)
    begin
                ap_predicate_op202_store_state5 <= ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_2));
    end process;


    ap_predicate_op204_store_state5_assign_proc : process(icmp_ln107_reg_1003, trunc_ln321_fu_849_p1)
    begin
                ap_predicate_op204_store_state5 <= ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_1));
    end process;


    ap_predicate_op206_store_state5_assign_proc : process(icmp_ln107_reg_1003, trunc_ln321_fu_849_p1)
    begin
                ap_predicate_op206_store_state5 <= ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_0));
    end process;


    ap_predicate_op208_store_state5_assign_proc : process(icmp_ln107_reg_1003, trunc_ln321_fu_849_p1)
    begin
                ap_predicate_op208_store_state5 <= ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_3));
    end process;


    ap_predicate_op216_load_state6_assign_proc : process(icmp_ln107_reg_1003_pp0_iter2_reg, icmp_ln123_reg_1007_pp0_iter2_reg)
    begin
                ap_predicate_op216_load_state6 <= ((icmp_ln107_reg_1003_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln123_reg_1007_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op217_load_state6_assign_proc : process(icmp_ln107_reg_1003_pp0_iter2_reg, icmp_ln123_reg_1007_pp0_iter2_reg)
    begin
                ap_predicate_op217_load_state6 <= ((icmp_ln107_reg_1003_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln123_reg_1007_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op218_load_state6_assign_proc : process(icmp_ln107_reg_1003_pp0_iter2_reg, icmp_ln123_reg_1007_pp0_iter2_reg)
    begin
                ap_predicate_op218_load_state6 <= ((icmp_ln107_reg_1003_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln123_reg_1007_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op219_load_state6_assign_proc : process(icmp_ln107_reg_1003_pp0_iter2_reg, icmp_ln123_reg_1007_pp0_iter2_reg)
    begin
                ap_predicate_op219_load_state6 <= ((icmp_ln107_reg_1003_pp0_iter2_reg = ap_const_lv1_0) and (icmp_ln123_reg_1007_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op221_write_state7_assign_proc : process(icmp_ln107_reg_1003_pp0_iter3_reg, icmp_ln123_reg_1007_pp0_iter3_reg)
    begin
                ap_predicate_op221_write_state7 <= ((icmp_ln107_reg_1003_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln123_reg_1007_pp0_iter3_reg = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ofm_y_1_i_load_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln107_reg_1003, icmp_ln123_reg_1007, icmp_ln132_reg_1021, icmp_ln135_reg_1025, icmp_ln138_reg_1029, icmp_ln141_reg_1033, ofm_y_1_i_fu_104, select_ln144_3_fu_783_p3)
    begin
        if (((icmp_ln123_reg_1007 = ap_const_lv1_1) and (icmp_ln141_reg_1033 = ap_const_lv1_1) and (icmp_ln138_reg_1029 = ap_const_lv1_1) and (icmp_ln135_reg_1025 = ap_const_lv1_1) and (icmp_ln132_reg_1021 = ap_const_lv1_1) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_ofm_y_1_i_load <= select_ln144_3_fu_783_p3;
        else 
            ap_sig_allocacmp_ofm_y_1_i_load <= ofm_y_1_i_fu_104;
        end if; 
    end process;

    bound_fu_442_p2 <= std_logic_vector(unsigned(p_shl_fu_427_p1) + unsigned(p_shl70_fu_438_p1));
    count_simd_fu_546_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(count_simd_4_fu_124));
    counter_internal_blo_16_fu_709_p2 <= std_logic_vector(unsigned(counter_internal_blo_fu_136) + unsigned(ap_const_lv32_1));
    current_block_write_21_fu_865_p3 <= 
        ap_const_lv32_0 when (icmp_ln116_fu_859_p2(0) = '1') else 
        current_block_write_fu_853_p2;
    current_block_write_22_fu_809_p2 <= std_logic_vector(unsigned(current_block_write_20_fu_128) + unsigned(ap_const_lv32_1));
    current_block_write_23_fu_821_p3 <= 
        ap_const_lv32_0 when (icmp_ln165_fu_815_p2(0) = '1') else 
        current_block_write_22_fu_809_p2;
    current_block_write_24_fu_829_p3 <= 
        current_block_write_23_fu_821_p3 when (icmp_ln160_reg_1051(0) = '1') else 
        current_block_write_20_fu_128;
    current_block_write_fu_853_p2 <= std_logic_vector(unsigned(current_block_write_20_fu_128) + unsigned(ap_const_lv32_1));
    current_line_in_bloc_fu_540_p2 <= std_logic_vector(unsigned(add_ln128_fu_534_p2) + unsigned(k_x_4_fu_120));
    grp_fu_372_p2 <= std_logic_vector(unsigned(current_line_8_fu_132) + unsigned(ap_const_lv32_1));
    i_fu_471_p3 <= 
        ap_const_lv14_1 when (icmp_ln105_fu_459_p2(0) = '1') else 
        add_ln105_fu_465_p2;
    icmp_ln104_fu_448_p2 <= "1" when (indvar_flatten_reg_307 = bound_reg_979) else "0";
    icmp_ln105_fu_459_p2 <= "1" when (i_0_i_reg_318 = ap_const_lv14_2004) else "0";
    icmp_ln107_fu_497_p2 <= "1" when (unsigned(inp_4_fu_116) < unsigned(ap_const_lv32_60)) else "0";
    icmp_ln113_fu_384_p2 <= "1" when (grp_fu_372_p2 = ap_const_lv32_20) else "0";
    icmp_ln116_fu_859_p2 <= "1" when (current_block_write_fu_853_p2 = ap_const_lv32_4) else "0";
    icmp_ln123_fu_506_p2 <= "1" when (unsigned(counter_internal_blo_fu_136) < unsigned(ap_const_lv32_10D)) else "0";
    icmp_ln132_fu_552_p2 <= "1" when (count_simd_4_fu_124 = ap_const_lv32_0) else "0";
    icmp_ln135_fu_569_p2 <= "1" when (k_x_fu_563_p2 = ap_const_lv32_3) else "0";
    icmp_ln138_fu_580_p2 <= "1" when (k_y_fu_528_p2 = ap_const_lv32_3) else "0";
    icmp_ln141_fu_600_p2 <= "1" when (ofm_x_fu_594_p2 = ap_const_lv32_1E) else "0";
    icmp_ln144_fu_620_p2 <= "1" when (ofm_y_fu_614_p2 = ap_const_lv32_1E) else "0";
    icmp_ln153_4_fu_658_p2 <= "1" when (tmp_1_fu_648_p4 = ap_const_lv27_0) else "0";
    icmp_ln153_fu_642_p2 <= "1" when (unsigned(counter_internal_blo_fu_136) < unsigned(ap_const_lv32_1F)) else "0";
    icmp_ln160_fu_378_p2 <= "1" when (grp_fu_372_p2 = ap_const_lv32_20) else "0";
    icmp_ln165_fu_815_p2 <= "1" when (current_block_write_22_fu_809_p2 = ap_const_lv32_4) else "0";
    icmp_ln172_fu_715_p2 <= "1" when (counter_internal_blo_16_fu_709_p2 = ap_const_lv32_10D) else "0";

    in_V_V_blk_n_assign_proc : process(in_V_V_empty_n, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln107_reg_1003, and_ln153_reg_1047)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            in_V_V_blk_n <= in_V_V_empty_n;
        else 
            in_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_V_read_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, ap_predicate_op167_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op167_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            in_V_V_read <= ap_const_logic_1;
        else 
            in_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    inp_fu_734_p2 <= std_logic_vector(unsigned(inp_4_fu_116) + unsigned(ap_const_lv32_1));
    inputBuf_0_V_address0 <= zext_ln129_fu_765_p1(5 - 1 downto 0);

    inputBuf_0_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln107_reg_1003, zext_ln156_fu_794_p1, zext_ln110_fu_841_p1, trunc_ln321_fu_849_p1, ap_condition_438)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_0))) then 
                inputBuf_0_V_address1 <= zext_ln110_fu_841_p1(5 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_438)) then 
                inputBuf_0_V_address1 <= zext_ln156_fu_794_p1(5 - 1 downto 0);
            else 
                inputBuf_0_V_address1 <= "XXXXX";
            end if;
        else 
            inputBuf_0_V_address1 <= "XXXXX";
        end if; 
    end process;


    inputBuf_0_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_0_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, and_ln153_reg_1047, ap_block_pp0_stage0_11001, trunc_ln321_18_fu_802_p1, trunc_ln321_fu_849_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_0_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, and_ln153_reg_1047, ap_block_pp0_stage0_11001, trunc_ln321_18_fu_802_p1, trunc_ln321_fu_849_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_0_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_1_V_address0 <= zext_ln129_fu_765_p1(5 - 1 downto 0);

    inputBuf_1_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln107_reg_1003, zext_ln156_fu_794_p1, zext_ln110_fu_841_p1, trunc_ln321_fu_849_p1, ap_condition_450)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_1))) then 
                inputBuf_1_V_address1 <= zext_ln110_fu_841_p1(5 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_450)) then 
                inputBuf_1_V_address1 <= zext_ln156_fu_794_p1(5 - 1 downto 0);
            else 
                inputBuf_1_V_address1 <= "XXXXX";
            end if;
        else 
            inputBuf_1_V_address1 <= "XXXXX";
        end if; 
    end process;


    inputBuf_1_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_1_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, and_ln153_reg_1047, ap_block_pp0_stage0_11001, trunc_ln321_18_fu_802_p1, trunc_ln321_fu_849_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_1_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, and_ln153_reg_1047, ap_block_pp0_stage0_11001, trunc_ln321_18_fu_802_p1, trunc_ln321_fu_849_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_1_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_2_V_address0 <= zext_ln129_fu_765_p1(5 - 1 downto 0);

    inputBuf_2_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln107_reg_1003, zext_ln156_fu_794_p1, zext_ln110_fu_841_p1, trunc_ln321_fu_849_p1, ap_condition_461)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_2))) then 
                inputBuf_2_V_address1 <= zext_ln110_fu_841_p1(5 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_461)) then 
                inputBuf_2_V_address1 <= zext_ln156_fu_794_p1(5 - 1 downto 0);
            else 
                inputBuf_2_V_address1 <= "XXXXX";
            end if;
        else 
            inputBuf_2_V_address1 <= "XXXXX";
        end if; 
    end process;


    inputBuf_2_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_2_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, and_ln153_reg_1047, ap_block_pp0_stage0_11001, trunc_ln321_18_fu_802_p1, trunc_ln321_fu_849_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_2_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, and_ln153_reg_1047, ap_block_pp0_stage0_11001, trunc_ln321_18_fu_802_p1, trunc_ln321_fu_849_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_2_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_3_V_address0 <= zext_ln129_fu_765_p1(5 - 1 downto 0);

    inputBuf_3_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, icmp_ln107_reg_1003, zext_ln156_fu_794_p1, zext_ln110_fu_841_p1, trunc_ln321_fu_849_p1, ap_condition_472)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_3))) then 
                inputBuf_3_V_address1 <= zext_ln110_fu_841_p1(5 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_472)) then 
                inputBuf_3_V_address1 <= zext_ln156_fu_794_p1(5 - 1 downto 0);
            else 
                inputBuf_3_V_address1 <= "XXXXX";
            end if;
        else 
            inputBuf_3_V_address1 <= "XXXXX";
        end if; 
    end process;


    inputBuf_3_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_3_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, and_ln153_reg_1047, ap_block_pp0_stage0_11001, trunc_ln321_18_fu_802_p1, trunc_ln321_fu_849_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_3_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln107_reg_1003, and_ln153_reg_1047, ap_block_pp0_stage0_11001, trunc_ln321_18_fu_802_p1, trunc_ln321_fu_849_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1047) and (icmp_ln107_reg_1003 = ap_const_lv1_0) and (trunc_ln321_18_fu_802_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_1003 = ap_const_lv1_1) and (trunc_ln321_fu_849_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_3_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_x_fu_563_p2 <= std_logic_vector(unsigned(k_x_4_fu_120) + unsigned(ap_const_lv32_1));
    k_y_fu_528_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(k_y_4_fu_112));

    numReps_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_blk_n <= numReps_empty_n;
        else 
            numReps_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    numReps_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_out_blk_n <= numReps_out_full_n;
        else 
            numReps_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    numReps_out_din <= numReps_dout;

    numReps_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_out_write <= ap_const_logic_1;
        else 
            numReps_out_write <= ap_const_logic_0;
        end if; 
    end process;


    numReps_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_read <= ap_const_logic_1;
        else 
            numReps_read <= ap_const_logic_0;
        end if; 
    end process;

    ofm_x_fu_594_p2 <= std_logic_vector(unsigned(ofm_x_4_fu_108) + unsigned(ap_const_lv32_1));
    ofm_y_fu_614_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ofm_y_1_i_load) + unsigned(ap_const_lv32_1));

    out_V_V_blk_n_assign_proc : process(out_V_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, icmp_ln107_reg_1003_pp0_iter3_reg, icmp_ln123_reg_1007_pp0_iter3_reg)
    begin
        if (((icmp_ln107_reg_1003_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln123_reg_1007_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_V_V_blk_n <= out_V_V_full_n;
        else 
            out_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_V_din <= outElem_V_reg_1091;

    out_V_V_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_predicate_op221_write_state7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op221_write_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_V_V_write <= ap_const_logic_1;
        else 
            out_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_shl70_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_431_p3),46));
    p_shl_fu_427_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_420_p3),46));
    read_block_9_fu_684_p3 <= 
        add_ln163_fu_670_p2 when (icmp_ln160_fu_378_p2(0) = '1') else 
        trunc_ln105_fu_493_p1;
    read_block_fu_750_p2 <= std_logic_vector(unsigned(select_ln105_fu_485_p3) + unsigned(ap_const_lv32_1));
    select_ln105_fu_485_p3 <= 
        ap_const_lv32_0 when (icmp_ln105_reg_993(0) = '1') else 
        read_block_8_fu_100;
    select_ln144_3_fu_783_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_reg_1042(0) = '1') else 
        ofm_y_reg_1037;
    select_ln144_fu_626_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_fu_620_p2(0) = '1') else 
        inp_4_fu_116;
    select_ln160_fu_676_p3 <= 
        ap_const_lv32_0 when (icmp_ln160_fu_378_p2(0) = '1') else 
        grp_fu_372_p2;
    select_ln172_fu_721_p3 <= 
        ap_const_lv32_0 when (icmp_ln172_fu_715_p2(0) = '1') else 
        counter_internal_blo_16_fu_709_p2;
    tmp_1_fu_648_p4 <= select_ln105_fu_485_p3(31 downto 5);
    tmp_fu_420_p3 <= (numReps_read_reg_973 & ap_const_lv13_0);
    tmp_s_fu_431_p3 <= (numReps_read_reg_973 & ap_const_lv2_0);
    trunc_ln105_fu_493_p1 <= select_ln105_fu_485_p3(6 - 1 downto 0);
    trunc_ln124_4_fu_761_p1 <= current_block_write_20_fu_128(2 - 1 downto 0);
    trunc_ln124_fu_524_p1 <= k_y_4_fu_112(2 - 1 downto 0);
    trunc_ln321_18_fu_802_p1 <= current_block_write_20_fu_128(2 - 1 downto 0);
    trunc_ln321_fu_849_p1 <= current_block_write_20_fu_128(2 - 1 downto 0);
    zext_ln110_fu_841_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_396),64));
    zext_ln129_fu_765_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_line_in_bloc_reg_1016),64));
    zext_ln156_fu_794_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_396),64));
    zext_ln160_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(read_block_9_fu_684_p3),32));
end behav;
