-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ConvolutionInputGene_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    in_V_V_empty_n : IN STD_LOGIC;
    in_V_V_read : OUT STD_LOGIC;
    out_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_V_V_full_n : IN STD_LOGIC;
    out_V_V_write : OUT STD_LOGIC;
    numReps_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    numReps_empty_n : IN STD_LOGIC;
    numReps_read : OUT STD_LOGIC;
    numReps_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    numReps_out_full_n : IN STD_LOGIC;
    numReps_out_write : OUT STD_LOGIC );
end;


architecture behav of ConvolutionInputGene_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv44_0 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000000000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv44_A74 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000000000000101001110100";
    constant ap_const_lv44_1 : STD_LOGIC_VECTOR (43 downto 0) := "00000000000000000000000000000000000000000001";
    constant ap_const_lv12_A74 : STD_LOGIC_VECTOR (11 downto 0) := "101001110100";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_D7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln107_reg_983 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_reg_1042 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_V_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln107_reg_983_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln123_reg_987_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal numReps_blk_n : STD_LOGIC;
    signal numReps_out_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_303 : STD_LOGIC_VECTOR (43 downto 0);
    signal i_0_i_reg_314 : STD_LOGIC_VECTOR (11 downto 0);
    signal reg_392 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state7_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op177_read_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter1 : BOOLEAN;
    signal ap_predicate_op226_write_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln104_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln153_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal numReps_read_reg_959 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_419_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal bound_reg_969 : STD_LOGIC_VECTOR (43 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln104_fu_430_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal icmp_ln123_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln124_fu_488_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln124_reg_991 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln132_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln132_reg_1016 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_1020 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_1024 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_reg_1028 : STD_LOGIC_VECTOR (0 downto 0);
    signal ofm_y_fu_602_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_y_reg_1032 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln144_fu_608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln144_reg_1037 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln160_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln160_reg_1046 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_1051 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_745_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal outElem_V_fu_768_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal outElem_V_reg_1060 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state7 : STD_LOGIC;
    signal inputBuf_0_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_0_V_ce0 : STD_LOGIC;
    signal inputBuf_0_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_0_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_0_V_ce1 : STD_LOGIC;
    signal inputBuf_0_V_we1 : STD_LOGIC;
    signal inputBuf_1_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_1_V_ce0 : STD_LOGIC;
    signal inputBuf_1_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_1_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_1_V_ce1 : STD_LOGIC;
    signal inputBuf_1_V_we1 : STD_LOGIC;
    signal inputBuf_2_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_2_V_ce0 : STD_LOGIC;
    signal inputBuf_2_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_2_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_2_V_ce1 : STD_LOGIC;
    signal inputBuf_2_V_we1 : STD_LOGIC;
    signal inputBuf_3_V_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_3_V_ce0 : STD_LOGIC;
    signal inputBuf_3_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_3_V_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal inputBuf_3_V_ce1 : STD_LOGIC;
    signal inputBuf_3_V_we1 : STD_LOGIC;
    signal zext_ln129_fu_526_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln156_fu_793_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln110_fu_840_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal read_block_10_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln105_fu_448_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln160_fu_670_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_fu_728_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_y_1_i_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln144_2_fu_782_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_ofm_y_1_i_load : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_x_5_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_x_fu_582_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_5_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_fu_492_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_5_fu_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln144_fu_614_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_fu_712_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_5_fu_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_fu_551_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_5_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_fu_534_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_25_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_29_fu_828_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_26_fu_864_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_10_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln160_fu_654_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_368_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter_internal_blo_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln172_fu_699_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln321_19_fu_801_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_fu_848_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_419_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_419_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln105_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln128_4_fu_502_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln128_fu_498_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln128_fu_506_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal shl_ln_fu_512_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_in_bloc_fu_520_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln153_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln153_2_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln105_fu_457_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln163_fu_648_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal read_block_11_fu_662_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal counter_internal_blo_20_fu_687_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln172_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln105_fu_739_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln124_5_fu_753_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln129_2_fu_757_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal outElem_V_fu_768_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_block_write_27_fu_808_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln165_fu_814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_block_write_28_fu_820_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_fu_852_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln116_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op79_load_state7 : BOOLEAN;
    signal ap_enable_operation_79 : BOOLEAN;
    signal ap_enable_state7_pp0_iter0_stage0 : BOOLEAN;
    signal ap_predicate_op167_load_state8 : BOOLEAN;
    signal ap_enable_operation_167 : BOOLEAN;
    signal ap_enable_state8_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op189_store_state8 : BOOLEAN;
    signal ap_enable_operation_189 : BOOLEAN;
    signal ap_predicate_op216_store_state8 : BOOLEAN;
    signal ap_enable_operation_216 : BOOLEAN;
    signal ap_predicate_op81_load_state7 : BOOLEAN;
    signal ap_enable_operation_81 : BOOLEAN;
    signal ap_predicate_op168_load_state8 : BOOLEAN;
    signal ap_enable_operation_168 : BOOLEAN;
    signal ap_predicate_op187_store_state8 : BOOLEAN;
    signal ap_enable_operation_187 : BOOLEAN;
    signal ap_predicate_op214_store_state8 : BOOLEAN;
    signal ap_enable_operation_214 : BOOLEAN;
    signal ap_predicate_op83_load_state7 : BOOLEAN;
    signal ap_enable_operation_83 : BOOLEAN;
    signal ap_predicate_op169_load_state8 : BOOLEAN;
    signal ap_enable_operation_169 : BOOLEAN;
    signal ap_predicate_op185_store_state8 : BOOLEAN;
    signal ap_enable_operation_185 : BOOLEAN;
    signal ap_predicate_op212_store_state8 : BOOLEAN;
    signal ap_enable_operation_212 : BOOLEAN;
    signal ap_predicate_op85_load_state7 : BOOLEAN;
    signal ap_enable_operation_85 : BOOLEAN;
    signal ap_predicate_op170_load_state8 : BOOLEAN;
    signal ap_enable_operation_170 : BOOLEAN;
    signal ap_predicate_op191_store_state8 : BOOLEAN;
    signal ap_enable_operation_191 : BOOLEAN;
    signal ap_predicate_op218_store_state8 : BOOLEAN;
    signal ap_enable_operation_218 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_419_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal ap_condition_426 : BOOLEAN;
    signal ap_condition_59 : BOOLEAN;
    signal ap_condition_438 : BOOLEAN;
    signal ap_condition_449 : BOOLEAN;
    signal ap_condition_460 : BOOLEAN;

    component BlackBoxJam_mul_3xdS IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;


    component BlackBoxJam_mux_4pcA IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ConvolutionInputGtde IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    inputBuf_0_V_U : component ConvolutionInputGtde
    generic map (
        DataWidth => 32,
        AddressRange => 28,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_0_V_address0,
        ce0 => inputBuf_0_V_ce0,
        q0 => inputBuf_0_V_q0,
        address1 => inputBuf_0_V_address1,
        ce1 => inputBuf_0_V_ce1,
        we1 => inputBuf_0_V_we1,
        d1 => in_V_V_dout);

    inputBuf_1_V_U : component ConvolutionInputGtde
    generic map (
        DataWidth => 32,
        AddressRange => 28,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_1_V_address0,
        ce0 => inputBuf_1_V_ce0,
        q0 => inputBuf_1_V_q0,
        address1 => inputBuf_1_V_address1,
        ce1 => inputBuf_1_V_ce1,
        we1 => inputBuf_1_V_we1,
        d1 => in_V_V_dout);

    inputBuf_2_V_U : component ConvolutionInputGtde
    generic map (
        DataWidth => 32,
        AddressRange => 28,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_2_V_address0,
        ce0 => inputBuf_2_V_ce0,
        q0 => inputBuf_2_V_q0,
        address1 => inputBuf_2_V_address1,
        ce1 => inputBuf_2_V_ce1,
        we1 => inputBuf_2_V_we1,
        d1 => in_V_V_dout);

    inputBuf_3_V_U : component ConvolutionInputGtde
    generic map (
        DataWidth => 32,
        AddressRange => 28,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_3_V_address0,
        ce0 => inputBuf_3_V_ce0,
        q0 => inputBuf_3_V_q0,
        address1 => inputBuf_3_V_address1,
        ce1 => inputBuf_3_V_ce1,
        we1 => inputBuf_3_V_we1,
        d1 => in_V_V_dout);

    BlackBoxJam_mul_3xdS_U192 : component BlackBoxJam_mul_3xdS
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 13,
        dout_WIDTH => 44)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_419_p0,
        din1 => grp_fu_419_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_419_p2);

    BlackBoxJam_mux_4pcA_U193 : component BlackBoxJam_mux_4pcA
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => inputBuf_0_V_q0,
        din1 => inputBuf_1_V_q0,
        din2 => inputBuf_2_V_q0,
        din3 => inputBuf_3_V_q0,
        din4 => outElem_V_fu_768_p5,
        dout => outElem_V_fu_768_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state7))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state7)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state7);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_simd_5_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln132_fu_540_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                count_simd_5_fu_120 <= count_simd_fu_534_p2;
            elsif ((((icmp_ln135_fu_557_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln138_fu_568_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln141_fu_588_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln141_fu_588_p2 = ap_const_lv1_1) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                count_simd_5_fu_120 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    counter_internal_blo_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                counter_internal_blo_fu_132 <= select_ln172_fu_699_p3;
            elsif ((((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln113_fu_380_p2 = ap_const_lv1_1) and (icmp_ln107_fu_461_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                counter_internal_blo_fu_132 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_block_write_25_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln113_reg_1051 = ap_const_lv1_1) and (icmp_ln107_reg_983 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_block_write_25_fu_124 <= current_block_write_26_fu_864_p3;
            elsif (((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_block_write_25_fu_124 <= current_block_write_29_fu_828_p3;
            elsif ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_block_write_25_fu_124 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_line_10_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln113_fu_380_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_line_10_fu_128 <= grp_fu_368_p2;
            elsif (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln153_fu_642_p2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_line_10_fu_128 <= select_ln160_fu_654_p3;
            elsif ((((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln113_fu_380_p2 = ap_const_lv1_1) and (icmp_ln107_fu_461_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                current_line_10_fu_128 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_0_i_reg_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_0_i_reg_314 <= i_fu_745_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_0_i_reg_314 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_303_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_303 <= add_ln104_fu_430_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                indvar_flatten_reg_303 <= ap_const_lv44_0;
            end if; 
        end if;
    end process;

    inp_5_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                inp_5_fu_112 <= inp_fu_712_p2;
            elsif (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln141_fu_588_p2 = ap_const_lv1_1) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                inp_5_fu_112 <= select_ln144_fu_614_p3;
            elsif ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                inp_5_fu_112 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_x_5_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln135_fu_557_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_x_5_fu_116 <= k_x_fu_551_p2;
            elsif ((((icmp_ln138_fu_568_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln141_fu_588_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln141_fu_588_p2 = ap_const_lv1_1) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_x_5_fu_116 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_y_5_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln138_fu_568_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_y_5_fu_108 <= k_y_fu_492_p2;
            elsif ((((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_y_5_fu_108 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_x_5_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln141_fu_588_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ofm_x_5_fu_104 <= ofm_x_fu_582_p2;
            elsif ((((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln141_fu_588_p2 = ap_const_lv1_1) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                ofm_x_5_fu_104 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_y_1_i_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_reg_987 = ap_const_lv1_1) and (icmp_ln141_reg_1028 = ap_const_lv1_1) and (icmp_ln138_reg_1024 = ap_const_lv1_1) and (icmp_ln135_reg_1020 = ap_const_lv1_1) and (icmp_ln132_reg_1016 = ap_const_lv1_1) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ofm_y_1_i_fu_100 <= select_ln144_2_fu_782_p3;
            elsif ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ofm_y_1_i_fu_100 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    read_block_10_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln113_fu_380_p2 = ap_const_lv1_1) and (icmp_ln107_fu_461_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                read_block_10_fu_96 <= read_block_fu_728_p2;
            elsif (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln153_fu_642_p2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                read_block_10_fu_96 <= zext_ln160_fu_670_p1;
            elsif ((((icmp_ln113_fu_380_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_lv1_0 = and_ln153_fu_642_p2) and (icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                read_block_10_fu_96 <= select_ln105_fu_448_p3;
            elsif ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                read_block_10_fu_96 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln153_reg_1042 <= and_ln153_fu_642_p2;
                icmp_ln123_reg_987 <= icmp_ln123_fu_470_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                bound_reg_969 <= grp_fu_419_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln107_reg_983 <= icmp_ln107_fu_461_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln107_reg_983_pp0_iter1_reg <= icmp_ln107_reg_983;
                icmp_ln123_reg_987_pp0_iter1_reg <= icmp_ln123_reg_987;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln113_reg_1051 <= icmp_ln113_fu_380_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln132_reg_1016 <= icmp_ln132_fu_540_p2;
                trunc_ln124_reg_991 <= trunc_ln124_fu_488_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln135_reg_1020 <= icmp_ln135_fu_557_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln138_reg_1024 <= icmp_ln138_fu_568_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln141_reg_1028 <= icmp_ln141_fu_588_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln141_fu_588_p2 = ap_const_lv1_1) and (icmp_ln138_fu_568_p2 = ap_const_lv1_1) and (icmp_ln135_fu_557_p2 = ap_const_lv1_1) and (icmp_ln132_fu_540_p2 = ap_const_lv1_1) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln144_reg_1037 <= icmp_ln144_fu_608_p2;
                ofm_y_reg_1032 <= ofm_y_fu_602_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln153_fu_642_p2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln160_reg_1046 <= icmp_ln160_fu_374_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                numReps_read_reg_959 <= numReps_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln123_reg_987 = ap_const_lv1_1) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                outElem_V_reg_1060 <= outElem_V_fu_768_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln107_fu_461_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln153_fu_642_p2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                reg_392 <= current_line_10_fu_128;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0, icmp_ln104_fu_425_p2, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln104_fu_425_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((icmp_ln104_fu_425_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln104_fu_430_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_303) + unsigned(ap_const_lv44_1));
    add_ln105_fu_739_p2 <= std_logic_vector(unsigned(i_0_i_reg_314) + unsigned(ap_const_lv12_1));
    add_ln128_fu_506_p2 <= std_logic_vector(unsigned(trunc_ln128_4_fu_502_p1) + unsigned(trunc_ln128_fu_498_p1));
    add_ln129_2_fu_757_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(trunc_ln124_5_fu_753_p1));
    add_ln163_fu_648_p2 <= std_logic_vector(unsigned(trunc_ln105_fu_457_p1) + unsigned(ap_const_lv4_1));
    and_ln153_fu_642_p2 <= (icmp_ln153_fu_630_p2 and icmp_ln153_2_fu_636_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(6);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(7);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, ap_enable_reg_pp0_iter2, ap_predicate_op177_read_state8, ap_predicate_op226_write_state9)
    begin
                ap_block_pp0_stage0_01001 <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op226_write_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op177_read_state8 = ap_const_boolean_1)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, ap_enable_reg_pp0_iter2, ap_predicate_op177_read_state8, ap_predicate_op226_write_state9)
    begin
                ap_block_pp0_stage0_11001 <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op226_write_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op177_read_state8 = ap_const_boolean_1)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, ap_enable_reg_pp0_iter2, ap_predicate_op177_read_state8, ap_predicate_op226_write_state9)
    begin
                ap_block_pp0_stage0_subdone <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op226_write_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op177_read_state8 = ap_const_boolean_1)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, numReps_empty_n, numReps_out_full_n)
    begin
                ap_block_state1 <= ((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state7_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter1_assign_proc : process(in_V_V_empty_n, icmp_ln107_reg_983, ap_predicate_op177_read_state8)
    begin
                ap_block_state8_pp0_stage0_iter1 <= (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op177_read_state8 = ap_const_boolean_1)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state9_pp0_stage0_iter2_assign_proc : process(out_V_V_full_n, ap_predicate_op226_write_state9)
    begin
                ap_block_state9_pp0_stage0_iter2 <= ((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op226_write_state9 = ap_const_boolean_1));
    end process;


    ap_condition_426_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042, trunc_ln321_19_fu_801_p1)
    begin
                ap_condition_426 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_0));
    end process;


    ap_condition_438_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042, trunc_ln321_19_fu_801_p1)
    begin
                ap_condition_438 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_1));
    end process;


    ap_condition_449_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042, trunc_ln321_19_fu_801_p1)
    begin
                ap_condition_449 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_2));
    end process;


    ap_condition_460_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042, trunc_ln321_19_fu_801_p1)
    begin
                ap_condition_460 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_3));
    end process;


    ap_condition_59_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_59 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_pp0_exit_iter0_state7_assign_proc : process(icmp_ln104_fu_425_p2)
    begin
        if ((icmp_ln104_fu_425_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state7 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_167_assign_proc : process(ap_predicate_op167_load_state8)
    begin
                ap_enable_operation_167 <= (ap_predicate_op167_load_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_168_assign_proc : process(ap_predicate_op168_load_state8)
    begin
                ap_enable_operation_168 <= (ap_predicate_op168_load_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_169_assign_proc : process(ap_predicate_op169_load_state8)
    begin
                ap_enable_operation_169 <= (ap_predicate_op169_load_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_170_assign_proc : process(ap_predicate_op170_load_state8)
    begin
                ap_enable_operation_170 <= (ap_predicate_op170_load_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_185_assign_proc : process(ap_predicate_op185_store_state8)
    begin
                ap_enable_operation_185 <= (ap_predicate_op185_store_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_187_assign_proc : process(ap_predicate_op187_store_state8)
    begin
                ap_enable_operation_187 <= (ap_predicate_op187_store_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_189_assign_proc : process(ap_predicate_op189_store_state8)
    begin
                ap_enable_operation_189 <= (ap_predicate_op189_store_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_191_assign_proc : process(ap_predicate_op191_store_state8)
    begin
                ap_enable_operation_191 <= (ap_predicate_op191_store_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_212_assign_proc : process(ap_predicate_op212_store_state8)
    begin
                ap_enable_operation_212 <= (ap_predicate_op212_store_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_214_assign_proc : process(ap_predicate_op214_store_state8)
    begin
                ap_enable_operation_214 <= (ap_predicate_op214_store_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_216_assign_proc : process(ap_predicate_op216_store_state8)
    begin
                ap_enable_operation_216 <= (ap_predicate_op216_store_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_218_assign_proc : process(ap_predicate_op218_store_state8)
    begin
                ap_enable_operation_218 <= (ap_predicate_op218_store_state8 = ap_const_boolean_1);
    end process;


    ap_enable_operation_79_assign_proc : process(ap_predicate_op79_load_state7)
    begin
                ap_enable_operation_79 <= (ap_predicate_op79_load_state7 = ap_const_boolean_1);
    end process;


    ap_enable_operation_81_assign_proc : process(ap_predicate_op81_load_state7)
    begin
                ap_enable_operation_81 <= (ap_predicate_op81_load_state7 = ap_const_boolean_1);
    end process;


    ap_enable_operation_83_assign_proc : process(ap_predicate_op83_load_state7)
    begin
                ap_enable_operation_83 <= (ap_predicate_op83_load_state7 = ap_const_boolean_1);
    end process;


    ap_enable_operation_85_assign_proc : process(ap_predicate_op85_load_state7)
    begin
                ap_enable_operation_85 <= (ap_predicate_op85_load_state7 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_state7_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
                ap_enable_state7_pp0_iter0_stage0 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state8_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state8_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op167_load_state8_assign_proc : process(icmp_ln107_reg_983, icmp_ln123_reg_987)
    begin
                ap_predicate_op167_load_state8 <= ((icmp_ln123_reg_987 = ap_const_lv1_1) and (icmp_ln107_reg_983 = ap_const_lv1_0));
    end process;


    ap_predicate_op168_load_state8_assign_proc : process(icmp_ln107_reg_983, icmp_ln123_reg_987)
    begin
                ap_predicate_op168_load_state8 <= ((icmp_ln123_reg_987 = ap_const_lv1_1) and (icmp_ln107_reg_983 = ap_const_lv1_0));
    end process;


    ap_predicate_op169_load_state8_assign_proc : process(icmp_ln107_reg_983, icmp_ln123_reg_987)
    begin
                ap_predicate_op169_load_state8 <= ((icmp_ln123_reg_987 = ap_const_lv1_1) and (icmp_ln107_reg_983 = ap_const_lv1_0));
    end process;


    ap_predicate_op170_load_state8_assign_proc : process(icmp_ln107_reg_983, icmp_ln123_reg_987)
    begin
                ap_predicate_op170_load_state8 <= ((icmp_ln123_reg_987 = ap_const_lv1_1) and (icmp_ln107_reg_983 = ap_const_lv1_0));
    end process;


    ap_predicate_op177_read_state8_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042)
    begin
                ap_predicate_op177_read_state8 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0));
    end process;


    ap_predicate_op185_store_state8_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042, trunc_ln321_19_fu_801_p1)
    begin
                ap_predicate_op185_store_state8 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_2));
    end process;


    ap_predicate_op187_store_state8_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042, trunc_ln321_19_fu_801_p1)
    begin
                ap_predicate_op187_store_state8 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_1));
    end process;


    ap_predicate_op189_store_state8_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042, trunc_ln321_19_fu_801_p1)
    begin
                ap_predicate_op189_store_state8 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_0));
    end process;


    ap_predicate_op191_store_state8_assign_proc : process(icmp_ln107_reg_983, and_ln153_reg_1042, trunc_ln321_19_fu_801_p1)
    begin
                ap_predicate_op191_store_state8 <= ((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_3));
    end process;


    ap_predicate_op212_store_state8_assign_proc : process(icmp_ln107_reg_983, trunc_ln321_fu_848_p1)
    begin
                ap_predicate_op212_store_state8 <= ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_2));
    end process;


    ap_predicate_op214_store_state8_assign_proc : process(icmp_ln107_reg_983, trunc_ln321_fu_848_p1)
    begin
                ap_predicate_op214_store_state8 <= ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_1));
    end process;


    ap_predicate_op216_store_state8_assign_proc : process(icmp_ln107_reg_983, trunc_ln321_fu_848_p1)
    begin
                ap_predicate_op216_store_state8 <= ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_0));
    end process;


    ap_predicate_op218_store_state8_assign_proc : process(icmp_ln107_reg_983, trunc_ln321_fu_848_p1)
    begin
                ap_predicate_op218_store_state8 <= ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_3));
    end process;


    ap_predicate_op226_write_state9_assign_proc : process(icmp_ln107_reg_983_pp0_iter1_reg, icmp_ln123_reg_987_pp0_iter1_reg)
    begin
                ap_predicate_op226_write_state9 <= ((icmp_ln107_reg_983_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln123_reg_987_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op79_load_state7_assign_proc : process(icmp_ln104_fu_425_p2, icmp_ln107_fu_461_p2, icmp_ln123_fu_470_p2)
    begin
                ap_predicate_op79_load_state7 <= ((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op81_load_state7_assign_proc : process(icmp_ln104_fu_425_p2, icmp_ln107_fu_461_p2, icmp_ln123_fu_470_p2)
    begin
                ap_predicate_op81_load_state7 <= ((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op83_load_state7_assign_proc : process(icmp_ln104_fu_425_p2, icmp_ln107_fu_461_p2, icmp_ln123_fu_470_p2)
    begin
                ap_predicate_op83_load_state7 <= ((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1));
    end process;


    ap_predicate_op85_load_state7_assign_proc : process(icmp_ln104_fu_425_p2, icmp_ln107_fu_461_p2, icmp_ln123_fu_470_p2)
    begin
                ap_predicate_op85_load_state7 <= ((icmp_ln107_fu_461_p2 = ap_const_lv1_0) and (icmp_ln104_fu_425_p2 = ap_const_lv1_0) and (icmp_ln123_fu_470_p2 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ofm_y_1_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln107_reg_983, icmp_ln123_reg_987, icmp_ln132_reg_1016, icmp_ln135_reg_1020, icmp_ln138_reg_1024, icmp_ln141_reg_1028, ofm_y_1_i_fu_100, select_ln144_2_fu_782_p3)
    begin
        if (((icmp_ln123_reg_987 = ap_const_lv1_1) and (icmp_ln141_reg_1028 = ap_const_lv1_1) and (icmp_ln138_reg_1024 = ap_const_lv1_1) and (icmp_ln135_reg_1020 = ap_const_lv1_1) and (icmp_ln132_reg_1016 = ap_const_lv1_1) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ofm_y_1_i_load <= select_ln144_2_fu_782_p3;
        else 
            ap_sig_allocacmp_ofm_y_1_i_load <= ofm_y_1_i_fu_100;
        end if; 
    end process;

    count_simd_fu_534_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(count_simd_5_fu_120));
    counter_internal_blo_20_fu_687_p2 <= std_logic_vector(unsigned(counter_internal_blo_fu_132) + unsigned(ap_const_lv32_1));
    current_block_write_26_fu_864_p3 <= 
        ap_const_lv32_0 when (icmp_ln116_fu_858_p2(0) = '1') else 
        current_block_write_fu_852_p2;
    current_block_write_27_fu_808_p2 <= std_logic_vector(unsigned(current_block_write_25_fu_124) + unsigned(ap_const_lv32_1));
    current_block_write_28_fu_820_p3 <= 
        ap_const_lv32_0 when (icmp_ln165_fu_814_p2(0) = '1') else 
        current_block_write_27_fu_808_p2;
    current_block_write_29_fu_828_p3 <= 
        current_block_write_28_fu_820_p3 when (icmp_ln160_reg_1046(0) = '1') else 
        current_block_write_25_fu_124;
    current_block_write_fu_852_p2 <= std_logic_vector(unsigned(current_block_write_25_fu_124) + unsigned(ap_const_lv32_1));
    current_line_in_bloc_fu_520_p2 <= std_logic_vector(unsigned(shl_ln_fu_512_p3) + unsigned(count_simd_5_fu_120));
    grp_fu_368_p2 <= std_logic_vector(unsigned(current_line_10_fu_128) + unsigned(ap_const_lv32_1));
    grp_fu_419_p0 <= grp_fu_419_p00(32 - 1 downto 0);
    grp_fu_419_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(numReps_read_reg_959),44));
    grp_fu_419_p1 <= ap_const_lv44_A74(13 - 1 downto 0);
    i_fu_745_p3 <= 
        ap_const_lv12_1 when (icmp_ln105_fu_442_p2(0) = '1') else 
        add_ln105_fu_739_p2;
    icmp_ln104_fu_425_p2 <= "1" when (indvar_flatten_reg_303 = bound_reg_969) else "0";
    icmp_ln105_fu_442_p2 <= "1" when (i_0_i_reg_314 = ap_const_lv12_A74) else "0";
    icmp_ln107_fu_461_p2 <= "1" when (unsigned(inp_5_fu_112) < unsigned(ap_const_lv32_54)) else "0";
    icmp_ln113_fu_380_p2 <= "1" when (grp_fu_368_p2 = ap_const_lv32_1C) else "0";
    icmp_ln116_fu_858_p2 <= "1" when (current_block_write_fu_852_p2 = ap_const_lv32_4) else "0";
    icmp_ln123_fu_470_p2 <= "1" when (unsigned(counter_internal_blo_fu_132) < unsigned(ap_const_lv32_D7)) else "0";
    icmp_ln132_fu_540_p2 <= "1" when (count_simd_fu_534_p2 = ap_const_lv32_2) else "0";
    icmp_ln135_fu_557_p2 <= "1" when (k_x_fu_551_p2 = ap_const_lv32_3) else "0";
    icmp_ln138_fu_568_p2 <= "1" when (k_y_fu_492_p2 = ap_const_lv32_3) else "0";
    icmp_ln141_fu_588_p2 <= "1" when (ofm_x_fu_582_p2 = ap_const_lv32_C) else "0";
    icmp_ln144_fu_608_p2 <= "1" when (ofm_y_fu_602_p2 = ap_const_lv32_C) else "0";
    icmp_ln153_2_fu_636_p2 <= "1" when (unsigned(select_ln105_fu_448_p3) < unsigned(ap_const_lv32_E)) else "0";
    icmp_ln153_fu_630_p2 <= "1" when (unsigned(counter_internal_blo_fu_132) < unsigned(ap_const_lv32_1B)) else "0";
    icmp_ln160_fu_374_p2 <= "1" when (grp_fu_368_p2 = ap_const_lv32_1C) else "0";
    icmp_ln165_fu_814_p2 <= "1" when (current_block_write_27_fu_808_p2 = ap_const_lv32_4) else "0";
    icmp_ln172_fu_693_p2 <= "1" when (counter_internal_blo_20_fu_687_p2 = ap_const_lv32_D7) else "0";

    in_V_V_blk_n_assign_proc : process(in_V_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln107_reg_983, and_ln153_reg_1042)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            in_V_V_blk_n <= in_V_V_empty_n;
        else 
            in_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, ap_predicate_op177_read_state8, ap_block_pp0_stage0_11001)
    begin
        if ((((icmp_ln107_reg_983 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op177_read_state8 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            in_V_V_read <= ap_const_logic_1;
        else 
            in_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    inp_fu_712_p2 <= std_logic_vector(unsigned(inp_5_fu_112) + unsigned(ap_const_lv32_1));
    inputBuf_0_V_address0 <= zext_ln129_fu_526_p1(5 - 1 downto 0);

    inputBuf_0_V_address1_assign_proc : process(icmp_ln107_reg_983, zext_ln156_fu_793_p1, zext_ln110_fu_840_p1, trunc_ln321_fu_848_p1, ap_condition_426, ap_condition_59)
    begin
        if ((ap_const_boolean_1 = ap_condition_59)) then
            if (((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_0))) then 
                inputBuf_0_V_address1 <= zext_ln110_fu_840_p1(5 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_426)) then 
                inputBuf_0_V_address1 <= zext_ln156_fu_793_p1(5 - 1 downto 0);
            else 
                inputBuf_0_V_address1 <= "XXXXX";
            end if;
        else 
            inputBuf_0_V_address1 <= "XXXXX";
        end if; 
    end process;


    inputBuf_0_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_0_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, and_ln153_reg_1042, ap_block_pp0_stage0_11001, trunc_ln321_19_fu_801_p1, trunc_ln321_fu_848_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_0_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, and_ln153_reg_1042, ap_block_pp0_stage0_11001, trunc_ln321_19_fu_801_p1, trunc_ln321_fu_848_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_0_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_1_V_address0 <= zext_ln129_fu_526_p1(5 - 1 downto 0);

    inputBuf_1_V_address1_assign_proc : process(icmp_ln107_reg_983, zext_ln156_fu_793_p1, zext_ln110_fu_840_p1, trunc_ln321_fu_848_p1, ap_condition_59, ap_condition_438)
    begin
        if ((ap_const_boolean_1 = ap_condition_59)) then
            if (((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_1))) then 
                inputBuf_1_V_address1 <= zext_ln110_fu_840_p1(5 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_438)) then 
                inputBuf_1_V_address1 <= zext_ln156_fu_793_p1(5 - 1 downto 0);
            else 
                inputBuf_1_V_address1 <= "XXXXX";
            end if;
        else 
            inputBuf_1_V_address1 <= "XXXXX";
        end if; 
    end process;


    inputBuf_1_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_1_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, and_ln153_reg_1042, ap_block_pp0_stage0_11001, trunc_ln321_19_fu_801_p1, trunc_ln321_fu_848_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_1_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, and_ln153_reg_1042, ap_block_pp0_stage0_11001, trunc_ln321_19_fu_801_p1, trunc_ln321_fu_848_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_1_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_2_V_address0 <= zext_ln129_fu_526_p1(5 - 1 downto 0);

    inputBuf_2_V_address1_assign_proc : process(icmp_ln107_reg_983, zext_ln156_fu_793_p1, zext_ln110_fu_840_p1, trunc_ln321_fu_848_p1, ap_condition_59, ap_condition_449)
    begin
        if ((ap_const_boolean_1 = ap_condition_59)) then
            if (((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_2))) then 
                inputBuf_2_V_address1 <= zext_ln110_fu_840_p1(5 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_449)) then 
                inputBuf_2_V_address1 <= zext_ln156_fu_793_p1(5 - 1 downto 0);
            else 
                inputBuf_2_V_address1 <= "XXXXX";
            end if;
        else 
            inputBuf_2_V_address1 <= "XXXXX";
        end if; 
    end process;


    inputBuf_2_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_2_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, and_ln153_reg_1042, ap_block_pp0_stage0_11001, trunc_ln321_19_fu_801_p1, trunc_ln321_fu_848_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_2_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, and_ln153_reg_1042, ap_block_pp0_stage0_11001, trunc_ln321_19_fu_801_p1, trunc_ln321_fu_848_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_2_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_3_V_address0 <= zext_ln129_fu_526_p1(5 - 1 downto 0);

    inputBuf_3_V_address1_assign_proc : process(icmp_ln107_reg_983, zext_ln156_fu_793_p1, zext_ln110_fu_840_p1, trunc_ln321_fu_848_p1, ap_condition_59, ap_condition_460)
    begin
        if ((ap_const_boolean_1 = ap_condition_59)) then
            if (((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_3))) then 
                inputBuf_3_V_address1 <= zext_ln110_fu_840_p1(5 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_460)) then 
                inputBuf_3_V_address1 <= zext_ln156_fu_793_p1(5 - 1 downto 0);
            else 
                inputBuf_3_V_address1 <= "XXXXX";
            end if;
        else 
            inputBuf_3_V_address1 <= "XXXXX";
        end if; 
    end process;


    inputBuf_3_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_3_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, and_ln153_reg_1042, ap_block_pp0_stage0_11001, trunc_ln321_19_fu_801_p1, trunc_ln321_fu_848_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_3_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln107_reg_983, and_ln153_reg_1042, ap_block_pp0_stage0_11001, trunc_ln321_19_fu_801_p1, trunc_ln321_fu_848_p1)
    begin
        if ((((ap_const_lv1_1 = and_ln153_reg_1042) and (icmp_ln107_reg_983 = ap_const_lv1_0) and (trunc_ln321_19_fu_801_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((icmp_ln107_reg_983 = ap_const_lv1_1) and (trunc_ln321_fu_848_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_3_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_x_fu_551_p2 <= std_logic_vector(unsigned(k_x_5_fu_116) + unsigned(ap_const_lv32_1));
    k_y_fu_492_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(k_y_5_fu_108));

    numReps_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_blk_n <= numReps_empty_n;
        else 
            numReps_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    numReps_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_out_blk_n <= numReps_out_full_n;
        else 
            numReps_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    numReps_out_din <= numReps_dout;

    numReps_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n)
    begin
        if ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_out_write <= ap_const_logic_1;
        else 
            numReps_out_write <= ap_const_logic_0;
        end if; 
    end process;


    numReps_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n)
    begin
        if ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_read <= ap_const_logic_1;
        else 
            numReps_read <= ap_const_logic_0;
        end if; 
    end process;

    ofm_x_fu_582_p2 <= std_logic_vector(unsigned(ofm_x_5_fu_104) + unsigned(ap_const_lv32_1));
    ofm_y_fu_602_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ofm_y_1_i_load) + unsigned(ap_const_lv32_1));
    outElem_V_fu_768_p5 <= std_logic_vector(unsigned(add_ln129_2_fu_757_p2) + unsigned(trunc_ln124_reg_991));

    out_V_V_blk_n_assign_proc : process(out_V_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln107_reg_983_pp0_iter1_reg, icmp_ln123_reg_987_pp0_iter1_reg)
    begin
        if (((icmp_ln107_reg_983_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln123_reg_987_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            out_V_V_blk_n <= out_V_V_full_n;
        else 
            out_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_V_din <= outElem_V_reg_1060;

    out_V_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op226_write_state9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op226_write_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_V_V_write <= ap_const_logic_1;
        else 
            out_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    read_block_11_fu_662_p3 <= 
        add_ln163_fu_648_p2 when (icmp_ln160_fu_374_p2(0) = '1') else 
        trunc_ln105_fu_457_p1;
    read_block_fu_728_p2 <= std_logic_vector(unsigned(select_ln105_fu_448_p3) + unsigned(ap_const_lv32_1));
    select_ln105_fu_448_p3 <= 
        ap_const_lv32_0 when (icmp_ln105_fu_442_p2(0) = '1') else 
        read_block_10_fu_96;
    select_ln144_2_fu_782_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_reg_1037(0) = '1') else 
        ofm_y_reg_1032;
    select_ln144_fu_614_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_fu_608_p2(0) = '1') else 
        inp_5_fu_112;
    select_ln160_fu_654_p3 <= 
        ap_const_lv32_0 when (icmp_ln160_fu_374_p2(0) = '1') else 
        grp_fu_368_p2;
    select_ln172_fu_699_p3 <= 
        ap_const_lv32_0 when (icmp_ln172_fu_693_p2(0) = '1') else 
        counter_internal_blo_20_fu_687_p2;
    shl_ln_fu_512_p3 <= (add_ln128_fu_506_p2 & ap_const_lv1_0);
    trunc_ln105_fu_457_p1 <= select_ln105_fu_448_p3(4 - 1 downto 0);
    trunc_ln124_5_fu_753_p1 <= current_block_write_25_fu_124(2 - 1 downto 0);
    trunc_ln124_fu_488_p1 <= k_y_5_fu_108(2 - 1 downto 0);
    trunc_ln128_4_fu_502_p1 <= ofm_x_5_fu_104(31 - 1 downto 0);
    trunc_ln128_fu_498_p1 <= k_x_5_fu_116(31 - 1 downto 0);
    trunc_ln321_19_fu_801_p1 <= current_block_write_25_fu_124(2 - 1 downto 0);
    trunc_ln321_fu_848_p1 <= current_block_write_25_fu_124(2 - 1 downto 0);
    zext_ln110_fu_840_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_392),64));
    zext_ln129_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_line_in_bloc_fu_520_p2),64));
    zext_ln156_fu_793_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_392),64));
    zext_ln160_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(read_block_11_fu_662_p3),32));
end behav;
